//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionValue
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> feature { get; set; }
        public byte[] leftValueIncluded { get; set; }
        public Nullable<double> leftVaue { get; set; }
        public Nullable<double> rightValue { get; set; }
        public byte[] rightValueIncluded { get; set; }
        public string unit { get; set; }
    
        public virtual Feature Feature1 { get; set; }
    }
}
