//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassDimensionValue> ClassDimensionValue { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<ClassLogicalValues> ClassLogicalValues { get; set; }
        public virtual DbSet<ClassScalarValues> ClassScalarValues { get; set; }
        public virtual DbSet<DimensionValue> DimensionValue { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<Feature_description> Feature_description { get; set; }
        public virtual DbSet<LogicalValues> LogicalValues { get; set; }
        public virtual DbSet<ScalarValues> ScalarValues { get; set; }
    }
}
